
conky.config = {
    alignment = 'top_right',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 60,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'normal',
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
    own_window_colour = '#000000',
    own_window_argb_visual = true,
    own_window_argb_value = 150,
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}

conky.text = [[
${color white}System:$color ${scroll 32 Conky $conky_version - $sysname $nodename $kernel $machine}
${color white} $alignc ${color grey}Uptime:$color $uptime
${color white} $alignc CPU/RAM:
${color white} $alignc ${cpugraph 80,150 1ff213 eb5717 -t} ${memgraph 80,150 1ff213 eb5717 -t}
${color white}RAM: $memperc% - $mem/$memeasyfree $hr

${color white}File system $hr
${color white}root    ${fs_used /}/${fs_size /} ${fs_bar 6 /}
${color white}home    $color${fs_used /home}/${fs_size /home} ${fs_bar 6 /home}
${color white}backup  $color${fs_used /mnt/backup/}/${fs_size /mnt/backup/} ${fs_bar 6 /mnt/backup/}

CPU: $cpu% $hr
${color white}Freq: ${freq} Mhz 
Scalling driver: ${cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver}
${color white}Scalling governor: ${cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor}
${color white}Energy preference: ${cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference}

Cooling $hr
${color white}Corsair Liquid: ${exec sensors | grep 'fan2' | cut -c27-34}
${color white}Noctua: ${exec sensors | grep 'fan4' | cut -c27-34}
${color white}Corsair QL: ${exec sensors | grep 'fan3' | cut -c27-34}

GPU $hr
Power: ${exec sensors | grep 'PPT' | cut -c15-21}
${color white}Fan: ${exec sensors | grep 'fan1' | tail -n1 | cut -c14-21} - ${exec sensors | grep 'pwm1' | tail -n1 | cut -c18-21}
${color white}GPU: ${exec sensors | grep 'sclk' | cut -c15-21} VRAM: ${exec sensors | grep 'mclk' | cut -c15-21}
]]
   

